#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug  5 16:23:06 2022

@author: nitin-mukesh
to make a program for pattern 
1
12
123
1234
"""


count=1
#line=int(input("Enter the number for the pattern"))
for i in range(1,5,1):
    for j in range(1,i,1):
        print(j,end=" ")
    print("")